/* kernel/gui/font.h - baked font tables (generated by tools/bake_font.py) */
#ifndef BORNOMALA_FONT_H
#define BORNOMALA_FONT_H

#include <stdint.h>

/* One anti-aliased glyph: an 8-bit coverage mask of w*h bytes at bitmap[off]. */
typedef struct {
    uint8_t  w, h;          /* mask size in pixels */
    int8_t   xoff, yoff;    /* mask top-left relative to the pen position ON THE BASELINE (yoff < 0 = above) */
    uint16_t adv16;         /* horizontal advance in 1/16 pixel */
    uint32_t off;           /* offset into bitmap[] */
} glyph_t;

typedef struct {
    int px;                 /* nominal pixel size */
    int ascent, descent;
    int cap;                /* height of a capital letter */
    int first, count;       /* first character code covered, and how many */
    const glyph_t *glyphs;
    const uint8_t *bitmap;
} font_t;

extern const font_t font_ui12, font_ui13, font_ui13b, font_ui16b, font_ui24;
extern const font_t font_clock144, font_clock104, font_clock76;
extern const font_t font_logo;               /* single glyph, code 1: Bengali 'ব' */

/* 8x16 monospace bitmap font, ASCII 32..126, one byte per row, MSB = left pixel. */
extern const uint8_t font_mono8x16[95][16];

#endif
